name: rtd_conda_test38
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - sphinx=3.4  # Can't be pinned by default, see https://github.com/readthedocs/readthedocs.org/issues/3829
